stages:
  - sync

sync-com-to-cn:
  stage: sync
  image: ubuntu:latest
  
  before_script:
    - apt-get update && apt-get install -y skopeo ca-certificates
    - update-ca-certificates
    
  script:
    - |
      # ⚠️【注意】：请把下面的 你的国际版用户名 替换成你 gitlab.com 的实际用户名
      # 如果你的国际版项目名不叫 docker，请把后面的 /docker/ 改成你的实际项目名
      COM_REGISTRY="registry.gitlab.com/tmzg0000/docker"
      
      IMAGES=(
        "jxxghp/moviepilot-v2:latest"
        "amilys/embyserver:latest"
        "amilys/embyserver_arm64v8:latest"
        "linuxserver/emby:latest"
        "linuxserver/transmission:latest"
        "nyanmisaka/jellyfin:latest"
        "snowdreamtech/frpc:latest"
        "iyuucn/iyuuplus-dev:latest"
        "dreamacro/clash:latest"
        "haishanh/yacd:latest"
        "metatube/metatube-server:latest"
        "mzz2017/v2raya:latest"
        "linuxserver/qbittorrent:latest"
        "linuxserver/transmission:4.0.5"
        "linuxserver/qbittorrent:4.6.7"
        "redis:latest"
        "postgres:latest"
        "metacubex/metacubexd:latest"
      )
    # 登录极狐国内本地的镜像仓库
    - echo "$CI_REGISTRY_PASSWORD" | skopeo login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - |
      for IMAGE in "${IMAGES[@]}"; do
        echo "----------------------------------------"
        # 直接从你的国际版私有库（海外源）拉取
        SRC_URL="docker://$COM_REGISTRY/$IMAGE"
        
        echo "正在跨海对拷: $SRC_URL -> 目标: $CI_REGISTRY_IMAGE/$IMAGE"
        
        # 执行对拷（添加 --src-tls-verify=false 确保跨境握手更稳）
        skopeo copy --all --src-tls-verify=false "$SRC_URL" "docker://$CI_REGISTRY_IMAGE/$IMAGE"
        
        if [ $? -eq 0 ]; then
          echo "✅ $IMAGE 跨境对拷成功！"
        else
          echo "❌ $IMAGE 跨境对拷失败！"
        fi
      done

  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'