[Application]
FileLogger\Age=1
FileLogger\AgeType=1
FileLogger\Backup=true
FileLogger\DeleteOld=true
FileLogger\Enabled=true
FileLogger\MaxSizeBytes=66560
FileLogger\Path=/config/qBittorrent/logs

[AutoRun]
enabled=false
program=

[BitTorrent]
Session\AddExtensionToIncompleteFiles=true
Session\AddTorrentStopped=false
Session\AlternativeGlobalDLSpeedLimit=10000
Session\AlternativeGlobalUPSpeedLimit=2000
Session\BandwidthSchedulerEnabled=true
Session\DefaultSavePath=/media/下载/电影
Session\ExcludedFileNames=
Session\IgnoreSlowTorrentsForQueueing=true
Session\MaxActiveDownloads=30
Session\MaxActiveTorrents=500
Session\MaxActiveUploads=300
Session\Port=50004
Session\QueueingSystemEnabled=true
Session\SSL\Port=59440
Session\ShareLimitAction=Stop
Session\Tags=MOVIEPILOT
Session\TempPath=/media/其他/正在下载
Session\TempPathEnabled=true
Session\UseAlternativeGlobalSpeedLimit=false

[Core]
AutoDeleteAddedTorrentFile=Never

[LegalNotice]
Accepted=true

[Meta]
MigrationVersion=8

[Network]
Cookies=@Invalid()
PortForwardingEnabled=true
Proxy\HostnameLookupEnabled=false
Proxy\Profiles\BitTorrent=true
Proxy\Profiles\Misc=true
Proxy\Profiles\RSS=true

[Preferences]
Connection\PortRangeMin=6881
Connection\UPnP=false
Downloads\SavePath=/downloads/
Downloads\TempPath=/downloads/incomplete/
General\Locale=zh_CN
MailNotification\req_auth=true
Scheduler\end_time=@Variant(\0\0\0\xf\x5%q\xa0)
Scheduler\start_time=@Variant(\0\0\0\xf\x3\xdc\xc5\0)
WebUI\Address=*
WebUI\CSRFProtection=false
WebUI\ClickjackingProtection=false
WebUI\HostHeaderValidation=false
WebUI\Password_PBKDF2="@ByteArray(PRU2q/Z1iw2cwaXvVN1MEw==:ZuhwYZx2nRqXDSg7US1eXzgM6cMEEf83VyeG8pb2dDmwcNBNV/fOR5OmCspSNubPpMETBVHbURTIPQaIFatiQw==)"
WebUI\Port=19990
WebUI\ServerDomains=*

[RSS]
AutoDownloader\DownloadRepacks=true
AutoDownloader\SmartEpisodeFilter=s(\\d+)e(\\d+), (\\d+)x(\\d+), "(\\d{4}[.\\-]\\d{1,2}[.\\-]\\d{1,2})", "(\\d{1,2}[.\\-]\\d{1,2}[.\\-]\\d{4})"
